apiVersion: skaffold/v2beta9
kind: Config
metadata:
  name: ticketing
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  artifacts:
  - image: brunnouw/auth
    context: auth
    sync:
      manual:
        - src: 'src/**/*.ts'
          dest: .
  - image: brunnouw/client
    context: client
    sync:
      manual:
        - src: '**/*.js'
          dest: .
