apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-depl
  labels:
    app: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: brunnouw/payments
        env:
          - name: NATS_CLIENT_ID
            valueFrom: 
              fieldRef:
                fieldPath: metadata.name
          - name: NATS_URL
            value: 'https://nats-serv:4222'
          - name: NATS_CLUSTER_ID
            value: ticketing
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: MONGO_URI
            value: 'mongodb://payments-mongo-srv:27017/payments'      
          - name: TZ
            valueFrom:
              secretKeyRef:
                name: custom-timezone
                key: TZ
          - name: STRIPE_KEY
            valueFrom:
              secretKeyRef:
                name: stripe-secret
                key: STRIPE_KEY
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: payments-serv
spec:
  type: ClusterIP
  selector:
    app: payments
  ports:
    - name: payments
      protocol: TCP
      port: 3000
      targetPort: 3000
      
